### ISSUE TITLE
How to download the dataset and features from Hugging Face?

### ISSUE THREAD

**Issue by Millielele** [CrystalSixone/VLN-GOAT#4]
Thanks for your great work!
I try to use python to download the files from the "https://huggingface.co/crystal61/VLN-GOAT".  But i encounter the problem like this :
requests.exceptions.ProxyError: HTTPSConnectionPool(host='e.aliendao.cn', port=443): Max retries exceeded with url: /models/crystal61/VLN-GOAT?json=true (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

Is there any other way to download these files?
Looking for your reply!

**Comment by CrystalSixone** [comment]
Hi, Thank you for your attention! 
It looks like you're encountering a ProxyError when downloading the files from Hugging Face using Python. This error is typically due to network or proxy settings on your end. You can try to manually download the files directly from the Hugging Face model page, by clicking on the "Files and versions" tab to download the files you need.
